spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://host.laness.net:3306/fuckingroulette?characterEncoding=UTF-8&serverTimezone=UTC
    username: roulette
    password: roulette!
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace
      org.hibernate.SQLQuery: debug

mail:
  address:
    admin: admin@gmail.com

jwt:
  secret-key: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY2NzMxMjMwOCwiaWF0IjoxNjY3MzEyMzA4fQ.ki5gEGWfkVOo08QGeYAAPEW4pfScj38Wz_uHsaUFOPI  # 민감한 정보는 시스템 환경 변수에서 로드한다.
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420